import { Exercise, WorkoutTemplate } from './types';

function youtubeSearch(query: string): string {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(`${query} Übung Ausführung`)}`;
}

export const SEED_EXERCISES: Exercise[] = [
  // Oberkörper
  { id: 'bankdruecken', name: 'Bankdrücken', category: 'oberkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Bankdrücken') },
  { id: 'latzug', name: 'Latzug', category: 'oberkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Latzug'), painAreas: ['nacken_schulter'] },
  { id: 'schulterdruecken', name: 'Schulterdrücken', category: 'oberkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Schulterdrücken'), painAreas: ['nacken_schulter'] },
  { id: 'rudern-kabelzug', name: 'Rudern (Kabelzug)', category: 'oberkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Rudern Kabelzug'), painAreas: ['nacken_schulter', 'ruecken'] },
  { id: 'bizepscurls', name: 'Bizepscurls', category: 'oberkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Bizepscurls') },
  { id: 'trizepsdruecken', name: 'Trizepsdrücken', category: 'oberkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Trizepsdrücken') },
  { id: 'klimmzuege', name: 'Klimmzüge', category: 'oberkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Klimmzüge'), painAreas: ['nacken_schulter'] },
  { id: 'liegestuetze', name: 'Liegestütze', category: 'oberkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Liegestütze') },

  // Unterkörper
  { id: 'kniebeuge', name: 'Kniebeuge', category: 'unterkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Kniebeuge'), painAreas: ['knie', 'huefte'] },
  { id: 'beinpresse', name: 'Beinpresse', category: 'unterkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Beinpresse'), painAreas: ['knie'] },
  { id: 'ausfallschritte', name: 'Ausfallschritte', category: 'unterkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Ausfallschritte'), painAreas: ['knie', 'huefte'] },
  { id: 'beinstrecker', name: 'Beinstrecker', category: 'unterkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Beinstrecker Maschine'), painAreas: ['knie', 'achillessehne'] },
  { id: 'beinbeuger', name: 'Beinbeuger', category: 'unterkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Beinbeuger Maschine'), painAreas: ['knie', 'ruecken', 'achillessehne'] },
  { id: 'wadenheben', name: 'Wadenheben', category: 'unterkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Wadenheben'), painAreas: ['achillessehne', 'plantarfaszie'] },
  { id: 'hueftabduktion', name: 'Hüftabduktion', category: 'unterkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Hüftabduktion Maschine'), painAreas: ['huefte', 'achillessehne'] },
  { id: 'kreuzheben', name: 'Kreuzheben', category: 'unterkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Kreuzheben'), painAreas: ['ruecken', 'huefte'] },

  // Protokollspezifische Übungen (evidenzbasierte Trainingsprotokolle je Schmerzbereich)
  {
    id: 'wadenheben-hsr',
    name: 'Wadenheben (HSR-Methode)',
    category: 'unterkoerper',
    logType: 'weight_reps',
    videoUrl: youtubeSearch('Heavy Slow Resistance Wadenheben Achillessehne'),
    painAreas: ['achillessehne'],
    note: 'Heavy Slow Resistance (Beyer et al.): 3 Sätze à 15 Wdh. mit einem Gewicht, das anfangs max. 15x schaffbar ist, im Verlauf der Wochen bis auf ca. 6 Wdh. steigern. Je 3 Sek. hoch, 3 Sek. runter, 3x/Woche. Sowohl mit gestrecktem als auch leicht gebeugtem Knie ausführen.',
  },
  {
    id: 'wadenheben-handtuch',
    name: 'Einbeiniges Wadenheben mit Handtuch (Rathleff-Methode)',
    category: 'unterkoerper',
    logType: 'weight_reps',
    videoUrl: youtubeSearch('High load strength training plantar fasciitis heel raise towel'),
    painAreas: ['plantarfaszie'],
    note: 'Zehen auf ein gerolltes Handtuch stellen, einbeinig ausführen. 3 Sek. hoch, 2 Sek. halten, 3 Sek. runter. Sobald 12 saubere Wiederholungen gelingen, Zusatzgewicht (z.B. Rucksack) ergänzen. Jeden 2. Tag.',
  },
  {
    id: 'decline-squat',
    name: 'Einbeinige Kniebeuge auf Schräge (Decline Squat)',
    category: 'unterkoerper',
    logType: 'weight_reps',
    videoUrl: youtubeSearch('Decline squat patellar tendinopathy protocol'),
    painAreas: ['knie'],
    note: 'Auf einer ca. 25°-Schräge (z.B. Keil) einbeinig langsam absenken (exzentrisch betont), mit dem freien Bein wieder hochstehen. 3 Sätze à 15 Wdh. Leichtes Training in den Schmerz hinein ist bei diesem Protokoll üblich, starker/zunehmender Schmerz ist ein Stopp-Signal.',
  },
  {
    id: 'hueftabduktion-isometrisch',
    name: 'Hüftabduktion isometrisch/HSR (Gesäßsehnen-Protokoll)',
    category: 'unterkoerper',
    logType: 'weight_reps',
    videoUrl: youtubeSearch('gluteal tendinopathy isometric hip abduction protocol'),
    painAreas: ['huefte'],
    note: 'Zur Schmerzlinderung zunächst isometrisch halten (z.B. 5x 30-45 Sek.), danach zu langsamen, schweren Sätzen übergehen (z.B. 3x8-12, 3 Sek. pro Wiederholung). Schmerzauslösende Positionen (starke Hüftadduktion, langes Sitzen mit übereinandergeschlagenen Beinen) zwischenzeitlich meiden.',
  },
  {
    id: 'aussenrotation-band',
    name: 'Schulter-Außenrotation mit Band',
    category: 'oberkoerper',
    logType: 'weight_reps',
    videoUrl: youtubeSearch('Shoulder external rotation band rotator cuff exercise'),
    painAreas: ['nacken_schulter'],
    note: 'Ellbogen eng am Körper, 90° gebeugt, Band langsam nach außen ziehen. 2-3 Sätze à 12-15 Wdh., 3x/Woche. Bewegung eher unterhalb Schulterhöhe, unterhalb der Schmerzgrenze bleiben.',
  },
  {
    id: 'mcgill-curl-up',
    name: 'Curl-Up (McGill)',
    category: 'ganzkoerper',
    logType: 'time',
    videoUrl: youtubeSearch('McGill curl up core exercise technique'),
    painAreas: ['ruecken'],
    note: 'Ein Bein gestreckt, das andere angewinkelt, Hände stützen die Lendenlordose. Rumpf nur leicht anheben (keine volle Aufrichtung), 8-10 Sek. halten. 5-3-1-Pyramide (5, dann 3, dann 1 Wiederholung) pro Seite.',
  },
  {
    id: 'mcgill-side-plank',
    name: 'Side Plank (McGill)',
    category: 'ganzkoerper',
    logType: 'time',
    videoUrl: youtubeSearch('McGill side plank core exercise technique'),
    painAreas: ['ruecken'],
    note: 'Unterarmstütz seitlich, Becken anheben, Körper bildet eine gerade Linie. 10-20 Sek. halten, 3 Wiederholungen pro Seite.',
  },
  {
    id: 'mcgill-bird-dog',
    name: 'Bird Dog',
    category: 'ganzkoerper',
    logType: 'time',
    videoUrl: youtubeSearch('Bird dog exercise technique core stability'),
    painAreas: ['ruecken'],
    note: 'Vierfüßlerstand, Arm und gegenüberliegendes Bein gleichzeitig ausstrecken, bis beide parallel zum Boden sind. 8-10 Sek. halten, ohne dass das Becken kippt. Seiten abwechseln.',
  },

  // Ganzkörper
  { id: 'plank', name: 'Plank', category: 'ganzkoerper', logType: 'time', videoUrl: youtubeSearch('Plank'), painAreas: ['ruecken', 'achillessehne'] },
  { id: 'burpees', name: 'Burpees', category: 'ganzkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Burpees') },
  { id: 'rudergeraet', name: 'Rudergerät (Cardio)', category: 'ganzkoerper', logType: 'time', videoUrl: youtubeSearch('Rudergerät Technik'), painAreas: ['ruecken', 'nacken_schulter'] },
  { id: 'radfahren', name: 'Radfahren (Cardio)', category: 'ganzkoerper', logType: 'time', videoUrl: youtubeSearch('Radfahren Ergometer'), painAreas: ['knie', 'huefte'] },
  { id: 'mountain-climbers', name: 'Mountain Climbers', category: 'ganzkoerper', logType: 'time', videoUrl: youtubeSearch('Mountain Climbers') },
  { id: 'kettlebell-swings', name: 'Kettlebell Swings', category: 'ganzkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Kettlebell Swings'), painAreas: ['huefte', 'ruecken'] },
  { id: 'springseil', name: 'Springseil', category: 'ganzkoerper', logType: 'time', videoUrl: youtubeSearch('Springseil Technik'), painAreas: ['achillessehne', 'plantarfaszie'] },
  { id: 'crunches', name: 'Crunches', category: 'ganzkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Crunches'), painAreas: ['ruecken'] },

  // Warm-up / Mobility
  { id: '90-90-switch', name: '90/90 Switch', category: 'warmup', logType: 'weight_reps', videoUrl: youtubeSearch('90/90 hip switch mobility'), painAreas: ['huefte'] },
  { id: 'hip-cars', name: 'Hip CARs', category: 'warmup', logType: 'weight_reps', videoUrl: youtubeSearch('Hip CARs controlled articular rotations'), painAreas: ['huefte'] },
  { id: 'glute-bridge', name: 'Glute Bridge', category: 'warmup', logType: 'weight_reps', videoUrl: youtubeSearch('Glute Bridge'), painAreas: ['huefte', 'ruecken'] },
  { id: 'hamstring-walkouts', name: 'Hamstring Walkouts', category: 'warmup', logType: 'weight_reps', videoUrl: youtubeSearch('Hamstring Walkouts warm up'), painAreas: ['ruecken', 'knie'] },
  { id: 'ankle-cars', name: 'Ankle CARs', category: 'warmup', logType: 'weight_reps', videoUrl: youtubeSearch('Ankle CARs controlled articular rotations'), painAreas: ['achillessehne', 'plantarfaszie'] },
  { id: 'radfahren-warmup', name: 'Radfahren (Warm-up)', category: 'warmup', logType: 'time', videoUrl: youtubeSearch('Radfahren Ergometer leichtes Einrollen') },
  { id: 'rudern-warmup', name: 'Rudern (Warm-up)', category: 'warmup', logType: 'time', videoUrl: youtubeSearch('Rudergerät leichtes Einrollen') },

  // Achillessehne / Knie / Hüfte — erweiterte Protokoll-Übungen
  {
    id: 'single-leg-seated-iso-calf-hold',
    name: 'Single Leg Seated Iso Calf Hold',
    category: 'unterkoerper',
    logType: 'time',
    videoUrl: youtubeSearch('Single leg seated isometric calf hold soleus'),
    painAreas: ['achillessehne'],
    note: 'Sitzend, ein Bein, Ferse anheben und die Position isometrisch halten (Soleus-Fokus). 3-4 Sätze à 30-45 Sek.',
  },
  {
    id: 'single-leg-leg-extension',
    name: 'Single Leg Leg Extension',
    category: 'unterkoerper',
    logType: 'weight_reps',
    videoUrl: youtubeSearch('Single leg extension machine'),
    painAreas: ['knie', 'achillessehne'],
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: 'unterkoerper',
    logType: 'weight_reps',
    videoUrl: youtubeSearch('Romanian Deadlift RDL Technik'),
    painAreas: ['huefte', 'ruecken'],
  },
  {
    id: 'dk-kb-side-bend',
    name: 'DB/KB Side Bend',
    category: 'ganzkoerper',
    logType: 'weight_reps',
    videoUrl: youtubeSearch('Dumbbell Side Bend Obliques'),
    painAreas: ['huefte', 'ruecken'],
  },
  {
    id: 'peroneus-beidbeinig',
    name: 'Peroneus beidbeinig',
    category: 'unterkoerper',
    logType: 'weight_reps',
    videoUrl: youtubeSearch('Peroneal muscle strengthening ankle eversion'),
    painAreas: ['achillessehne', 'plantarfaszie'],
  },
  {
    id: 'kb-seated-tibialis-raise',
    name: 'Kettlebell Seated Tibialis Raise',
    category: 'unterkoerper',
    logType: 'weight_reps',
    videoUrl: youtubeSearch('Seated tibialis raise ankle dorsiflexion'),
    painAreas: ['achillessehne', 'plantarfaszie', 'knie'],
  },

  // Training AS 2 / AS 3 — weitere Achillessehne-Übungen
  { id: 'hip-airplanes', name: 'Hip Airplanes', category: 'warmup', logType: 'weight_reps', videoUrl: youtubeSearch('Hip Airplanes exercise balance'), painAreas: ['huefte'] },
  { id: 'hand-supported-single-leg-db-rdl', name: 'Hand Supported Single Leg DB RDL', category: 'unterkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Hand supported single leg RDL dumbbell'), painAreas: ['huefte', 'ruecken'] },
  { id: 'standing-cable-wood-choppers', name: 'Standing Cable Wood Choppers', category: 'ganzkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Standing Cable Wood Choppers Technik'), painAreas: ['huefte', 'ruecken'] },
  { id: 'hand-supported-db-bulgarian-split-squat', name: 'Hand Supported DB Bulgarian Split Squat', category: 'unterkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Hand supported Bulgarian Split Squat dumbbell'), painAreas: ['knie', 'huefte'] },
  { id: 'dead-bug-kb-pullover', name: 'Dead Bug w/KB Pullover', category: 'ganzkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Dead Bug Kettlebell Pullover core'), painAreas: ['ruecken'] },
  { id: 'tibialis-anterior-tap-tap', name: 'Tibialis Anterior Tap Tap', category: 'unterkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Tibialis anterior tap tap raise'), painAreas: ['achillessehne', 'plantarfaszie', 'knie'] },
  { id: 'single-leg-glute-bridge-iso-hold', name: 'Single Leg Glute Bridge Iso Hold', category: 'warmup', logType: 'time', videoUrl: youtubeSearch('Single leg glute bridge isometric hold'), painAreas: ['huefte', 'ruecken'] },
  { id: 'toe-elevated-calf-raise', name: 'Toe Elevated Calf Raise', category: 'unterkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Toe elevated deficit calf raise'), painAreas: ['achillessehne'] },
  { id: 'staggered-stance-hip-thrust', name: 'Staggered Stance Hip Thrust', category: 'unterkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Staggered stance hip thrust Technik'), painAreas: ['huefte'] },
  { id: 'adduktionsmaschine', name: 'Adduktionsmaschine', category: 'unterkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Adduktionsmaschine'), painAreas: ['huefte'] },
  { id: 'tibialis-posterior-training', name: 'Tibialis Posterior Training', category: 'unterkoerper', logType: 'weight_reps', videoUrl: youtubeSearch('Tibialis posterior strengthening inversion'), painAreas: ['achillessehne', 'plantarfaszie'] },
];

export const SEED_WORKOUT_TEMPLATES: WorkoutTemplate[] = [
  {
    id: 'oberkoerper-basic',
    name: 'Oberkörper Basic',
    category: 'oberkoerper',
    exerciseIds: ['bankdruecken', 'latzug', 'schulterdruecken', 'bizepscurls', 'trizepsdruecken'],
  },
  {
    id: 'unterkoerper-basic',
    name: 'Unterkörper Basic',
    category: 'unterkoerper',
    exerciseIds: ['kniebeuge', 'beinpresse', 'ausfallschritte', 'wadenheben'],
  },
  {
    id: 'ganzkoerper-basic',
    name: 'Ganzkörper Basic',
    category: 'ganzkoerper',
    exerciseIds: ['plank', 'kettlebell-swings', 'burpees', 'crunches'],
  },
  {
    id: 'warmup-routine',
    name: 'Warm-up Routine',
    category: 'warmup',
    exerciseIds: ['90-90-switch', 'hip-cars', 'glute-bridge', 'hamstring-walkouts', 'ankle-cars'],
  },
  {
    id: 'training-as-1',
    name: 'Training AS 1',
    category: 'unterkoerper',
    exerciseIds: [
      '90-90-switch',
      'hip-cars',
      'glute-bridge',
      'hamstring-walkouts',
      'ankle-cars',
      'single-leg-seated-iso-calf-hold',
      'single-leg-leg-extension',
      'romanian-deadlift',
      'dk-kb-side-bend',
      'beinstrecker',
      'peroneus-beidbeinig',
      'kb-seated-tibialis-raise',
    ],
    painAreas: ['achillessehne'],
  },
  {
    id: 'training-as-2',
    name: 'Training AS 2',
    category: 'unterkoerper',
    exerciseIds: [
      'ankle-cars',
      'hip-airplanes',
      'wadenheben-hsr',
      'hand-supported-single-leg-db-rdl',
      'standing-cable-wood-choppers',
      'hand-supported-db-bulgarian-split-squat',
      'dead-bug-kb-pullover',
      'tibialis-anterior-tap-tap',
    ],
    painAreas: ['achillessehne'],
  },
  {
    id: 'training-as-3',
    name: 'Training AS 3',
    category: 'unterkoerper',
    exerciseIds: [
      'hip-airplanes',
      'single-leg-glute-bridge-iso-hold',
      'toe-elevated-calf-raise',
      'staggered-stance-hip-thrust',
      'adduktionsmaschine',
      'hueftabduktion',
      'beinpresse',
      'tibialis-posterior-training',
    ],
    painAreas: ['achillessehne'],
  },
];
